#!/bin/sh

if [ ! -z "$(command -v konsoleprofile)" ]; then
    konsoleprofile ColorScheme=OneDark
    $@
    konsoleprofile ColorScheme=OneDarkTransparent
    sleep 0.1
    xprop -f _KDE_NET_WM_BLUR_BEHIND_REGION 32c -set _KDE_NET_WM_BLUR_BEHIND_REGION 0 -id $(xdotool getactivewindow)
else
    $@
fi

